### ISSUE TITLE
OkJson versioning

### ISSUE THREAD

**Issue by voxik** [kr/okjson#9]
Would it be possible to version OkJson somehow? For example in heroku-api, I see just this commit [1] with messaged "vendor latest okjson", but it is hard to know what okjson it actually was. I would appreciate, if that could be easier deductible. Thank you for considering.

[1] https://github.com/heroku/heroku.rb/commit/065b275e6eaf87b49d0fc630a5939c580dd6ecd9#lib/heroku/api/vendor

**Comment by voxik** [comment]
@sferik Could you please follow this practice? Last few merges did not updated the Upstream constant. Thank you.

**Comment by sferik** [comment]
@voxik Yeah, I’ll bump it now.

**Comment by voxik** [comment]
@sferik thx
